### ISSUE TITLE
Hardware Button LED's stuck on + Inconsistent Access to Google Assistant UI

### ISSUE THREAD

**Issue by MattieX** [xLexip/pe#12]
**Bug Description:**
1 - On the latest update 2021-02-06 when using hardware buttons (default behaviour) and not gestures the hardware buttons are always LED backlit and I cannot find an option to disable this.

2 - When using Google Assistant on the latest update it accessing the UI is inconsistent and not reliable. Asking via voice will not trigger the Assistant UI until you have finished your question and it responds, as a result it's hard to know if it's even listening to you at all or if it heard you accurately until afterwards.
This is observed when A) Accessing Assistant via the long-press of the Home Button (on the on-screen buttons); B) via swiping in from the corners when using on-screen gestures and C) When accessing via the assistant shortcut button on the home page 

**How to reproduce:**
1 - Install the latest version and observe that the hardware buttons are lit and cannot be disabled from an option in settings
2 - Install the latest version and observe that Google Assistant does not work as expected in terms of when the UI should show; this was not present on the previous version.

**Expected behaviour:**
1 - Expect hardware buttons to not be lit or at least have an option to toggle this behaviour
2 - Have google assistant trigger the UI via the three triggers mentioned above (A/B/C) and show the UI so that you can ask a question and see it being written on the screen before your request is dealt with.

**Device:**
 - Model: Cheeseburger (5)
 - Build date: 2021-02-06
 - Rooted: Yes - Magisk V21.4
 - Stock Kernel

**Additional context:**
I have tested this by updating from the old system following the instructions here: https://telegra.ph/How-to-update-Pixel-Experience-12-05. This was using the F2FS Filesystem

I have also wiped:
✔ Dalvik / ART Cache 
✔ Cache
✔ System
✔ Vendor 
✔ Data
+ Set the filesystem of /data back to EXT4
And reinstalled and set up the OS fresh and have observed the same behaviour.

Sidenote: Thanks for making this great Rom; it makes the OP5 feel really fluid.

**Comment by xLexip** [comment]
Thanks for the detailed report.

1 - I will take a look a this problem. I only have a 5T so I'm dependent on testers for cheeseburger. So the default behavioris that the buttons turn off after a few seconds?

2 -  The assistant UI is working fine for me... Maybe the problem is also caused by #9 or by the changed navigation for cheeseburger. Try if a reset if the Google App (clear all data) fixes the problem and please keep me updated.

**Comment by xLexip** [comment]
Thanks for the detailed report.

1 - I will take a look a this problem. I only have a 5T so I'm dependent on testers for cheeseburger. So the default behavioris that the buttons turn off after a few seconds?

2 -  The assistant UI is working fine for me... Maybe the problem is also caused by #9 or by the changed navigation for cheeseburger. Try if a reset if the Google App (clear all data) fixes the problem and please keep me updated.

**Comment by MattieX** [comment]
> Thanks for the detailed report.
> 
> 1 - I will take a look a this problem. I only have a 5T so I'm dependent on testers for cheeseburger. So the default behavioris that the buttons turn off after a few seconds?
> 
> 2 - The assistant UI is working fine for me... Maybe the problem is also caused by #9 or by the changed navigation for cheeseburger. Try if a reset if the Google App (clear all data) fixes the problem and please keep me updated.

1 - Thanks for taking a look, I appreciate it must be difficult without a device to hand. As I'm not daily driving this I'm happy to flash anything if it will help diagnose the issue. Apologies for not being more clear, the default behaviour observed is that the lights are on and will turn off if nothing is touched after approximately 10 seconds. 
The lights will turn back on if you touch either the hardware buttons or any portion of the screen hence why initially I did not realise that the lights do actually turn off if you stop touching the device. 

2 - I have been playing around with Resetting the Google app a lot today; I have found it to be mostly stable (after clearing data) so long as I don't ask it a question that triggers the non-pixel (Generic assistant UI) such as "Play xxx on Spotify". When responding to this question, you will see the generic assistant UI and with any subsequent questions you won't see the pixel style Assistant UI anymore until you clear data. I managed to replicate this behaviour 3 times of asking that question and clearing data, however I certainly understand that this does not help with exactly diagnosing a bug or not but I thought I would let you know my findings anyway. 
For reference, each time I am accessing the google assistant in the same way - pressing the assistant button on the google bar at the bottom of the home screen

**Comment by xLexip** [comment]
1 -  I'll see what I can do

2 - I guess you got the famous "new (pixel) assistant" because I've made the device look like a Pixel 5.
That new version only shows the UI if it is needed. So if you ask a math question or ask for the weather it should show the UI. But if you ask it to play something of spotify, it skips the UI what makes the general process faster, right?

**Comment by xLexip** [comment]
_No response, probably fixed._
