### ISSUE TITLE
Call screening does not work

### ISSUE THREAD

**Issue by err53** [xLexip/pe#17]
**Bug Description:**
The call screening feature appears and seems to load, but the caller does not hear the assistant, and no transcripts are generated. The voice of the caller is heard in the earpiece, however. Furthermore, selecting a voice causes the "Preparing Call Screen" to load indefinitely.

**How to reproduce:**
1. Call the phone with Pixel Experience
2. Select "Screen call" 

**Expected behavior:**
The call screening feature should play the assistant's voice to the caller, and should generate transcripts on the device.

**Device:**
 - Model: Dumpling (5T)
 - Build date: 20210409-1345
 - Rooted: no

**Comment by xLexip** [comment]
Call screening is not a ROM feature. Some users get this feature, because their device impersonates as a Pixel 5. Depending on the country, A/B testing luck, etc. people either get specific features or not. Call screening is not officially built in the rom and it isnt made for the OP5 so it's likely that it doesnt work properly. Nevertheless, the issue will be automatically reported to google anyway. Even if it would be a rom feature, this issue is on googles side.
